image: wonko21/fdroidserver:latest

before_script:
  - echo "$KEYSTORE" | base64 -d > fdroid/keystore.p12
  - chmod a+x download.py
  - chmod 600 fdroid/config.yml fdroid/keystore.p12
  - mkdir -p fdroid/repo

pages:
  stage: deploy
  script:
    - (cd fdroid/repo && while read -r line || [ -n "$line" ]; do rm -f $line; done < ../../cleanup.txt)
    - ./download.py
    - cd fdroid
    - update
    - mkdir /fdroid
    - fdroid deploy
    - rm -rf /fdroid/archive
    - cd .. && mkdir public && mv -v /fdroid public
  artifacts:
    paths:
      - public
    expire_in: 2 days
  only:
    - master
  cache:
    paths:
    - fdroid/repo/*.apk
