image: ubuntu:rolling

pages:
  stage: deploy
  before_script:
    - add-apt-repository ppa:fdroid/fdroidserver
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -y fdroidserver wget
    - echo "$KEYSTORE" | base64 -d > fdroid/keystore.p12
    - chmod a+x download.py
    - mkdir -p fdroid/repo
  script:
    - ./download.py
    - cd fdroid
    - fdroid update
    - rm -rf archive
    - mkdir /fdroid && fdroid server update
    - rm -rf /fdroid/archive
    - cd .. && mkdir public && mv -v /fdroid public
    - echo "Repo size:" && du -h -d 3 public
    - ls -al public/fdroid/repo/
  artifacts:
    paths:
      - public
  only:
    - master
