image:
  name: registry.gitlab.com/fdroid/docker-executable-fdroidserver:master
  entrypoint: [""]

before_script:
  - . /etc/profile.d/bsenv.sh
  - GRADLE_USER_HOME=${home_vagrant}/.gradle
  - echo "$KEYSTORE" | base64 -d > fdroid/keystore.p12
  - chmod 600 fdroid/config.yml fdroid/keystore.p12

pages:
  stage: deploy
  script:
    - ./download.py
    - cd fdroid
    - ${fdroidserver}/fdroid update
    - mkdir /fdroid
    - ${fdroidserver}/fdroid deploy
    - rm -rf /fdroid/archive
    - cd ..
    - mkdir public
    - mv -v /fdroid/* public/
    - cp index.html public/repo/
  cache:
    key: repo-cache
    paths:
      - fdroid/repo/*
      - versioncache.json
  artifacts:
    paths:
      - public
    expire_in: 2 days
  only:
    - master
